### ISSUE TITLE
something wrong with container.Config

### ISSUE THREAD

**Issue by zhaohaihang** [qingwave/weave#19]
Hi, in the `ContainerConfig()` function, the created container cannot open the console without adding the `OpenStdin` parameter. What is the reason for this, please?  such as:
```
 config := &container.Config{
		Image:        con.Image,
		Cmd:          con.Cmd,
		
		OpenStdin:    true,

		Labels: labels,
	}

**Comment by qingwave** [comment]
The `OpenStdin` config sames with the flag `-i` in docker cli, regarding the `container.Config` that just for create and run container in the backend we do not need set the Openstdin.
If you want to exec to the container, please see [exec function](https://github.com/qingwave/weave/blob/27c3cb7467b399a53250d07b32da1aa53006c5e2/pkg/controller/container.go#L316)

If there are still some concerns, please attach the detail example to reproduce your case and what you are expected.
