### ISSUE TITLE
Makefile搭建Docker+postgres，执行命令后进入容器无法退出

### ISSUE THREAD

**Issue by LWD8** [qingwave/weave#8]
单独运行：
make postgres

一直停留在容器里无法退出，也无法执行Makefile的其他命令。查了半天，但好像网上没搜索到答案，所以有人知道是怎么退出容器的吗：

![image](https://user-images.githubusercontent.com/28432674/178119253-94844dd0-c946-4aa0-871e-dc70f9703103.png)

**Comment by LWD8** [comment]
处理好了，首页IP地址写错了，大意。还有就是没把防火墙的5432端口打开。

firewall-cmd --zone=public --add-port=5432/tcp --permanent
重启
systemctl restart firewalld.service

**Comment by LWD8** [comment]
不过现在有另一个问题，是需要输入密码停在那里，继续踩地雷，一步一个坑

![image](https://user-images.githubusercontent.com/28432674/178129211-8eff1e3b-d5af-4fd8-aeb8-33fe9744dab7.png)

**Comment by qingwave** [comment]
这里只是在docker中安装Postgres，没什么特殊的，报错是因为你更改了Makefile，请参考最新版运气，或者自己手动执行
