### ISSUE TITLE
windows 下web编译出错，得把/src 换成 ./src才🆗

### ISSUE THREAD

**Issue by shaokeke** [qingwave/weave#9]
vite v2.7.10 building for production...
✓ 8 modules transformed.
[vite:load-fallback] Could not load C:\src/utils (imported by src\router\index.js): ENOENT: no such file or directory, open 'C:\src\utils'
error during build:

**Comment by shaokeke** [comment]
已start支持一下，但是第一次运行不了，体验会很差

**Comment by qingwave** [comment]
> 已start支持一下，但是第一次运行不了，体验会很差

多谢提醒，Win环境还没试过，后面我整理下
