### ISSUE TITLE
[Bug]: 401 error

### ISSUE THREAD

**Issue by kevinleee1128** [qingwave/weave#98]
**Describe the bug**
![1706609992000](https://github.com/qingwave/weave/assets/51021175/852836a6-9104-445b-8733-040e072ce5f2)
![1706609992000](https://github.com/qingwave/weave/assets/51021175/eca79f31-ee79-4697-8dd8-d48316d392aa)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment(please complete the following information):**
 - OS: [e.g. Linux 4.19]
 - Browser [e.g. chrome]
 - Golang Version [e.g. 1.18]

**Additional context**

**Comment by kevinleee1128** [comment]
![1706610090546](https://github.com/qingwave/weave/assets/51021175/5535915b-b9c7-487c-8bb3-bc31429753a6)
根据你的说明，curl 出现401

**Comment by kevinleee1128** [comment]
![image](https://github.com/qingwave/weave/assets/51021175/d21af7ba-2d12-444c-914a-c5e99ded08dd)

**Comment by kevinleee1128** [comment]
这两条curl 都返回401；
大佬有接口文档么

**Comment by kevinleee1128** [comment]
![image](https://github.com/qingwave/weave/assets/51021175/30025f91-9685-42ea-8ea9-22a51d0e5d66)
这块测试刚开始要填什么auth

**Comment by kevinleee1128** [comment]
所有接口功能

**Comment by kevinleee1128** [comment]
正常不应该谁都可以注册吗，为什么注册都出现401 error ？？

**Comment by qingwave** [comment]
我看一下，能提供下你是怎么安装的吗，页面登录正常不，看起来是数据库没有初始成功，admin user都不存在

**Comment by qingwave** [comment]
Hi @kevinleee1128 , 刚验证了下安装Readme步骤去启动没有问题的，你可以重新再试下，如果还有报错检查下Log是否正常

**Comment by kevinleee1128** [comment]
> Hi @kevinleee1128 , 刚验证了下安装Readme步骤去启动没有问题的，你可以重新再试下，如果还有报错检查下Log是否正常

![image](https://github.com/qingwave/weave/assets/51021175/2a258070-ecf1-4458-a38a-6bebbaf01437)
这是在linux下的，后端没有问题；
但是我在windows环境下会报错401，你的admin是怎么初始化的？在win下如何初始化postgresql呢？

**Comment by kevinleee1128** [comment]
> 我看一下，能提供下你是怎么安装的吗，页面登录正常不，看起来是数据库没有初始成功，admin user都不存在

我是在win下本地编译运行的，本地安装的postgresql

**Comment by qingwave** [comment]
可以参考下数据初始化脚本 https://github.com/qingwave/weave/blob/master/Makefile#L57
```
# 运行db.sql脚本
cat scripts/db.sql | docker exec -i mypostgres psql -U postgres
```

**Comment by qingwave** [comment]
> > 可以参考下数据初始化脚本 https://github.com/qingwave/weave/blob/master/Makefile#L57
> > ```
> > # 运行db.sql脚本
> > cat scripts/db.sql | docker exec -i mypostgres psql -U postgres
> > ```
> 
> 我本地win10环境没有用docker起postgresql； 用的安装包启动的postgresql，配置了账号，可以正常调用接口，就是一直报error401

直接在你的数据库运行sql脚本就可以 https://raw.githubusercontent.com/qingwave/weave/master/scripts/db.sql

**Comment by kevinleee1128** [comment]
> > > 可以参考下数据初始化脚本 https://github.com/qingwave/weave/blob/master/Makefile#L57
> > > ```
> > > # 运行db.sql脚本
> > > cat scripts/db.sql | docker exec -i mypostgres psql -U postgres
> > > ```
> > 
> > 
> > 我本地win10环境没有用docker起postgresql； 用的安装包启动的postgresql，配置了账号，可以正常调用接口，就是一直报error401
> 
> 直接在你的数据库运行sql脚本就可以 https://raw.githubusercontent.com/qingwave/weave/master/scripts/db.sql

好的，感谢大佬！

**Comment by kevinleee1128** [comment]
> > > 可以参考下数据初始化脚本 https://github.com/qingwave/weave/blob/master/Makefile#L57
> > > ```
> > > # 运行db.sql脚本
> > > cat scripts/db.sql | docker exec -i mypostgres psql -U postgres
> > > ```
> > 
> > 
> > 我本地win10环境没有用docker起postgresql； 用的安装包启动的postgresql，配置了账号，可以正常调用接口，就是一直报error401
> 
> 直接在你的数据库运行sql脚本就可以 https://raw.githubusercontent.com/qingwave/weave/master/scripts/db.sql

另外麻烦问下，后端接口服务只能本地测试吗，我用远程测试接口，显示连接不上

**Comment by qingwave** [comment]
这里改成'0.0.0.0' https://github.com/qingwave/weave/blob/20f5769eb25bc5b6a29eb23c5a79cc50248a9e9c/config/app.yaml#L3

**Comment by kevinleee1128** [comment]
> 这里改成'0.0.0.0'
> 
> https://github.com/qingwave/weave/blob/20f5769eb25bc5b6a29eb23c5a79cc50248a9e9c/config/app.yaml#L3

(๑•̀ㅂ•́)و✧

**Comment by kevinleee1128** [comment]
![image](https://github.com/qingwave/weave/assets/51021175/820c2f86-a721-4e69-b3b2-26a4d81e5f86)
github oauth error；是密钥填错了吗

**Comment by qingwave** [comment]
其他问题请检查日志和配置说明，大部分情况里面都涉及有
